name: CI
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
  pull_request:
    branches: [ main, master ]
  push:
env:
  JAVA_VERSION: 1.8
jobs:
  test-01-non-secured-drugstore-app:
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - run: cd $GITHUB_WORKSPACE/01-non-secured-drugstore-app ; ./mvnw -B dependency:resolve dependency:resolve-plugins
  test-01-secured-drugstore-app:
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - run: cd $GITHUB_WORKSPACE/01-secured-drugstore-app ; docker run --rm --name keycloack-01 -d -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:15.0.2
      - run: cd $GITHUB_WORKSPACE/01-secured-drugstore-app ; ./mvnw -B dependency:resolve dependency:resolve-plugins
      - run: cd $GITHUB_WORKSPACE/01-secured-drugstore-app ; docker rm -f -v `docker ps -aq`
  dependency-updates-01-non-secured-drugstore-app:
    if: contains(github.event.inputs.trigger, 'non-secured-drugstore-app')
      || startsWith(github.event.inputs.trigger, '01')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "Trigger: ${{ github.event.inputs.trigger }}"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - run: cd $GITHUB_WORKSPACE/${{ github.event.inputs.trigger }} ; ./mvnw -B dependency:resolve dependency:resolve-plugins
      - run: cd $GITHUB_WORKSPACE/${{ github.event.inputs.trigger }} ; ./mvnw versions:display-property-updates
      - run: cd $GITHUB_WORKSPACE/${{ github.event.inputs.trigger }} ; ./mvnw versions:display-plugin-updates
      - run: cd $GITHUB_WORKSPACE/${{ github.event.inputs.trigger }} ; ./mvnw versions:display-parent-updates
